zookeeper:
  image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
  net: host
  environment:
     - MYID=1
     - SERVERS=localhost

master:
  image: mesoscloud/mesos-master:0.24.1-ubuntu-14.04
  net: host
  environment:
    - MESOS_HOSTNAME=localhost
    - MESOS_IP=127.0.0.1
    - MESOS_QUORUM=1
    - MESOS_ZK=zk://localhost:2181/mesos

slave:
  image: mesoscloud/mesos-slave:0.24.1-ubuntu-14.04
  net: host
  privileged: true
  environment:
    - MESOS_HOSTNAME=localhost
    - MESOS_IP=127.0.0.1
    - MESOS_MASTER=zk://localhost:2181/mesos
    - MESOS_CONTAINERIZERS=docker,mesos
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /var/run/docker.sock:/var/run/docker.sock

marathon:
  image: mesoscloud/marathon:0.11.0-ubuntu-15.04
  net: host
  environment:
    - MARATHON_HOSTNAME=127.0.0.1
    - MARATHON_HTTPS_ADDRESS=127.0.0.1
    - MARATHON_HTTP_ADDRESS=127.0.0.1
    - MARATHON_MASTER=zk://localhost:2181/mesos
    - MARATHON_ZK=zk://localhost:2181/marathon

chronos:
  image: mesoscloud/chronos:2.4.0-ubuntu-14.04
  net: host
  environment:
   - CHRONOS_HTTP_PORT=4400
   - CHRONOS_MASTER=zk://localhost:2181/mesos
   - CHRONOS_ZK_HOSTS=localhost:2181
    
bamboo:
  net: host
  image: luprzybyl/bamboo:0.2.15
  environment:
   - MARATHON_ENDPOINT=http://localhost:8080
   - BAMBOO_ENDPOINT=http://localhsot:8000
   - BAMBOO_ZK_HOST=localhost:2181
   - BAMBOO_ZK_PATH=/bamboo
   - BAMBOO_DOCKER_AUTO_HOST=true

